<?php
require_once("../config/auth.php");require_once("../config/DataBase.php");require_once("../config/permissions.php");requireRole(["Admin","Manager","Employee"]);
$date=$_GET['date']??date('Y-m-d');
$employees=$conn->prepare("SELECT e.id,e.employee_number,e.fullname,a.status,a.check_in,a.check_out FROM employees e LEFT JOIN attendance a ON a.employee_id=e.id AND a.attendance_date=? WHERE e.status<>'Inactive' ORDER BY e.fullname ASC");
$employees->bind_param('s',$date);$employees->execute();$rows=$employees->get_result();
$total=(int)$conn->query("SELECT COUNT(*) total FROM employees WHERE status<>'Inactive'")->fetch_assoc()['total'];
$marked=(int)$conn->query("SELECT COUNT(*) total FROM attendance a INNER JOIN employees e ON e.id=a.employee_id WHERE a.attendance_date='".$conn->real_escape_string($date)."' AND a.status IN ('Present','Late') AND e.status<>'Inactive'")->fetch_assoc()['total'];
function attendanceBadge($s){if($s==='Present')return 'active';if($s==='Late')return 'leave';if($s==='Absent')return 'inactive';if($s==='Leave')return 'status-onleave';return '';}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>OpsFlow | Attendance</title><link rel="stylesheet" href="../Assets/CSS/style.css"><link rel="stylesheet" href="../Assets/CSS/dashboard.css"></head>
<body><div class="dashboard"><?php include("../Includes/sidebar.php"); ?><main class="main-content"><?php include("../Includes/header.php"); ?>
<section class="page-heading"><div class="page-toolbar"><div><h1>Attendance</h1><p><?php echo $marked; ?> of <?php echo $total; ?> marked present on <?php echo date('d M Y',strtotime($date)); ?></p></div><div class="actions"><form class="attendance-toolbar" method="get"><input class="attendance-date" type="date" name="date" value="<?php echo htmlspecialchars($date); ?>" onchange="this.form.submit()"></form><a href="../Reports/exports/export_attendance.php" class="btn btn-light"><i class="fa-solid fa-download"></i> Export</a></div></div></section>
<div class="content-card flush"><table class="attendance-table"><thead><tr><th>Employee</th><th>Check in</th><th>Check out</th><th>Status</th><th>Mark</th></tr></thead><tbody>
<?php while($r=$rows->fetch_assoc()){ ?><tr><td><div class="employee-name"><?php echo htmlspecialchars($r['fullname']); ?></div><span class="employee-no"><?php echo htmlspecialchars($r['employee_number']); ?></span></td><td><?php echo $r['check_in']?htmlspecialchars(substr($r['check_in'],0,5)):'—'; ?></td><td><?php echo $r['check_out']?htmlspecialchars(substr($r['check_out'],0,5)):'—'; ?></td><td><?php if($r['status']){ ?><span class="badge <?php echo attendanceBadge($r['status']); ?>"><?php echo $r['status']==='Leave'?'On Leave':htmlspecialchars($r['status']); ?></span><?php }else{ ?><span class="muted">Not marked</span><?php } ?></td><td><?php if(in_array($_SESSION['role'],['Admin','Manager'],true)){ ?><form action="save.php" method="post"><input type="hidden" name="employee_id" value="<?php echo (int)$r['id']; ?>"><input type="hidden" name="attendance_date" value="<?php echo htmlspecialchars($date); ?>"><select class="mark-select" name="status" onchange="this.form.submit()"><option value="">Select</option><option value="Present" <?php echo $r['status']==='Present'?'selected':''; ?>>Present</option><option value="Late" <?php echo $r['status']==='Late'?'selected':''; ?>>Late</option><option value="Absent" <?php echo $r['status']==='Absent'?'selected':''; ?>>Absent</option><option value="Leave" <?php echo $r['status']==='Leave'?'selected':''; ?>>On Leave</option></select></form><?php }else{ ?><span class="muted">View only</span><?php } ?></td></tr><?php } ?></tbody></table></div>
</main></div></body></html>
